FROM node:20
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

# Expose the port that the Vite app will use (modify if needed)
EXPOSE 5173

# Define the default comma nd to run when the container starts
CMD ["npm", "run", "dev"]
