version: '3'
services:
  vite:
    build:
      context: .
      dockerfile: Dockerfile.vite
    command: npm run dev
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - '5173:5173'
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_HOST: 'db'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: devices
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
  http:
    build:
      context: .
      dockerfile: Dockerfile.http
    command: npm run http
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - '3000:3000'
  data-loader:
    image: mysql:8.0
    depends_on:
      - db
    volumes:
      - ./src/server/db/schema:/docker-entrypoint-initdb.d
      - ./src/server/db/data:/docker-entrypoint-initdb.d
volumes:
  db:
    driver: local
